include $(LEVEL)/Makefile.config

GOALS = clean depends all install test
.PHONY: $(GOALS) subdirs $(SUBDIRS) $(RUN_TESTS)
.DEFAULT_GOAL := all
.DELETE_ON_ERROR :=

CC_COMMAND = $(CC) -c $(CFLAGS)
CXX_COMMAND = $(CXX) -c $(CXXFLAGS)

CC_MM_COMMAND = $(CC) $(CFLAGS) -MM
CXX_MM_COMMAND = $(CXX) $(CXXFLAGS) -MM

%.c.o: %.c .%.c.o.deps $(LEVEL)/Makefile.config
	$(CC_COMMAND) -o $@ $<

%.cpp.o: %.cpp .%.cpp.o.deps $(LEVEL)/Makefile.config
	$(CXX_COMMAND) -o $@ $<

.%.c.o.deps: %.c $(LEVEL)/Makefile.config
	$(CC_MM_COMMAND) -MM $< > $@
.%.cpp.o.deps: %.cpp $(LEVEL)/Makefile.config
	$(CXX_MM_COMMAND) -MM $< > $@

DEPENDENCIES := $(patsubst %,.%.deps,$(OBJECTS))
depends: $(DEPENDENCIES)
	-rm .depends
	cat $(DEPENDENCIES) > .depends
	rm $(DEPENDENCIES)

ifneq ($(MAKECMDGOALS),clean)
-include .depends
endif

all: $(TARGET)

clean: subdirs
	-rm -f $(OBJECTS) $(TARGET)

subdirs: $(SUBDIRS)

test: $(RUN_TESTS) subdirs

CMDGOALS := $(filter $(GOALS),$(MAKECMDGOALS))

$(SUBDIRS):
	$(MAKE) $(CMDGOALS) $(MAKEFLAGS) -C $@