CC=clang
CXX=clang++
LD=clang++
AR=ar

BISON=bison
FLEX=flex

BASE_FLAGS=-I$(LEVEL)/include $(INCLUDES) -O0 -g -Wall -Werror -DDEBUG
CFLAGS=$(BASE_FLAGS) -Wno-unused -fexceptions
CXXFLAGS=$(BASE_FLAGS) -Wno-unused -std=c++0x -stdlib=libc++ -fno-rtti -fexceptions -I../..
LDFLAGS=-O0 -g -dead_strip -lreadline -stdlib=libc++

# TODO: Make this cross-platform
DYNAMIC_LIBRARY_EXT=dylib
