CC=clang
CXX=clang++
LD=clang++
AR=ar

BISON=bison
FLEX=flex

BASE_FLAGS=-I$(LEVEL)/include $(INCLUDES) -Wall -Werror -Wno-unused -fexceptions -fPIC

DEBUG_FLAGS=$(BASE_FLAGS) -O0 -g -DDEBUG
RELEASE_FLAGS=$(BASE_FLAGS) -Os -g -fomit-frame-pointer -pipe
PROFILE_FLAGS=$(BASE_FLAGS) -Os -g

COMPILATION_FLAGS=$(DEBUG_FLAGS)

CFLAGS=$(COMPILATION_FLAGS)
CXXFLAGS=$(COMPILATION_FLAGS) -std=c++0x -stdlib=libc++ -fno-rtti -I../..
LDFLAGS=$(COMPILATION_FLAGS) -dead_strip -lreadline -stdlib=libc++

# TODO: Make this cross-platform
DYNAMIC_LIBRARY_EXT=dylib
