include $(LEVEL)/Makefile.config

GOALS = clean depends all install test
.PHONY: $(GOALS) subdirs $(SUBDIRS) $(RUN_TESTS)
.DEFAULT_GOAL := all
.DELETE_ON_ERROR :=

CC_COMMAND = $(CC) -c $(CFLAGS)
CXX_COMMAND = $(CXX) -c $(CXXFLAGS)

CC_MM_COMMAND = $(CC) $(CFLAGS) -MM
CXX_MM_COMMAND = $(CXX) $(CXXFLAGS) -MM

%.c.o: %.c .%.c.deps $(LEVEL)/Makefile.config
	$(CC_COMMAND) -o $@ $<

%.cpp.o: %.cpp .%.cpp.deps $(LEVEL)/Makefile.config
	$(CXX_COMMAND) -o $@ $<

.%.c.deps: %.c $(LEVEL)/Makefile.config
	@$(CC_MM_COMMAND) -MM $< | sed -e 's:\($*\)\.o[ \:]:\1.c.o $@\::g' > $@
.%.cpp.deps: %.cpp $(LEVEL)/Makefile.config
	@$(CXX_MM_COMMAND) -MM $< | sed -e 's:\($*\)\.o[ \:]:\1.cpp.o $@\::g' > $@

DEPENDENCIES := $(patsubst %,.%.deps,$(SOURCES))

ifneq ($(MAKECMDGOALS),clean)
-include $(DEPENDENCIES)
endif

all: $(TARGET)

clean: subdirs
	-rm -f $(OBJECTS) $(TARGET) $(DEPENDENCIES)

subdirs: $(SUBDIRS)

test: $(RUN_TESTS) subdirs

CMDGOALS := $(filter $(GOALS),$(MAKECMDGOALS))

$(SUBDIRS):
	$(MAKE) $(CMDGOALS) $(MAKEFLAGS) -C $@